# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# #   Character.create(name: 'Luke', movie: movies.first)




Ingredient.create(name: "ice", category: "juice")
Ingredient.create(name: "milk", category: "juice")
Ingredient.create(name: "tomato juice", category: "juice")
Ingredient.create(name: "orange juice", category: "juice")
Ingredient.create(name: "Coke", category: "juice")
Ingredient.create(name: "7up", category: "juice")
Ingredient.create(name: "tonic", category: "juice")
Ingredient.create(name: "coffee", category: "juice")
Ingredient.create(name: "water", category: "juice")
Ingredient.create(name: "cranberry juice", category: "juice")
Ingredient.create(name: "apple juice", category: "juice")
Ingredient.create(name: "grape juice", category: "juice")
Ingredient.create(name: "egg", category: "fruit")
Ingredient.create(name: "honey", category: "fruit")
Ingredient.create(name: "mint leaves", category: "fruit")
Ingredient.create(name: "avocado", category: "fruit")
Ingredient.create(name: "cherry", category: "fruit")
Ingredient.create(name: "straberry",  category: "fruit")
Ingredient.create(name: "celery", category: "fruit")
Ingredient.create(name: "cucumber",  category: "fruit")
Ingredient.create(name: "olive",  category: "fruit")
Ingredient.create(name: "lemon", category: "fruit")
Ingredient.create(name: "cinammon", category: "spice")
Ingredient.create(name: "sugar", category: "spice")
Ingredient.create(name: "salt", category: "spice")
Ingredient.create(name: "tabasco", category: "spice")
Ingredient.create(name: "vodka", category: "alcohol")
Ingredient.create(name: "rum", category: "alcohol")
Ingredient.create(name: "gin", category: "alcohol")
Ingredient.create(name: "tequila", category: "alcohol")
Ingredient.create(name: "Scotch", category: "alcohol")
Ingredient.create(name: "cognac", category: "alcohol")
Ingredient.create(name: "absinth", category: "alcohol")
Ingredient.create(name: "amarula", category: "alcohol")
Ingredient.create(name: "baileys", category: "alcohol")
Ingredient.create(name: "frangelico", category: "alcohol")
Ingredient.create(name: "midori", category: "alcohol")
Ingredient.create(name: "soho", category: "alcohol")
Ingredient.create(name: "chambord", category: "alcohol")
Ingredient.create(name: "malibu", category: "alcohol")
Ingredient.create(name: "fireball", category: "alcohol")
Ingredient.create(name: "grand marnier", category: "alcohol")
Ingredient.create(name: "sour puss", category: "alcohol")
Ingredient.create(name: "white wine", category: "alcohol")

Cocktail.create(name: "mojito", image: "xj8dize3gkifwdojcohc.jpg")
Cocktail.create(name: "cuba libre", image: "j2jlccgwfhfnf0suzh60.jpg")
Cocktail.create(name: "cosmo", image: "fddjfhj7gbrbfiuwayvh.jpg")
Cocktail.create(name: "sangria", image: "qh3gcohqqx4qnoqstlfs.jpg")
Cocktail.create(name: "bloody caesar", image: "rngjkotndpnhi6mfoj1m.jpg")
Cocktail.create(name: "tequila sunrise", image: "ectjqr7xkavpdsmmvpwa.jpg")
